### ISSUE TITLE
Comm

### ISSUE THREAD

**Issue by KwinEsther** [Darth-Jade-i/alx-backend#1]
https://intranet.alxswe.com/corrections/63604215/correct

**Comment by KwinEsther** [comment]
https://intranet.alxswe.com/corrections/63604215/correct

**Comment by KwinEsther** [comment]
https://intranet.alxswe.com/corrections/63607882/correct

**Comment by Darth-Jade-i** [comment]
Got the message

**Comment by KwinEsther** [comment]
https://intranet.alxswe.com/corrections/64166338/correct

**Comment by KwinEsther** [comment]
https://intranet.alxswe.com/corrections/64253134/correct
